name: Contango GUI CI

on:
    pull_request:
      branches: [main]
    push:
      branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm ci

    - name: Lint
      run: npm run lint

    - name: Tests
      run: npm test

    - name: Build
      run: npm run build
